language: php

matrix:
    include:
        - php: 7.1

script:
  - vendor/bin/simple-phpunit --coverage-clover=coverage.clover

before_script:
    - composer install
    - mysql -uroot -e 'CREATE DATABASE spoon_tests'
    - mysql -uroot -e "CREATE USER 'spoon'@'localhost' IDENTIFIED BY 'spoon'"
    - mysql -uroot -e "GRANT ALL PRIVILEGES ON spoon_tests.* TO 'spoon'@'localhost'"
    - mysql -uroot -e 'FLUSH PRIVILEGES'

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

sudo: false
